<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_631d3cde00311',
	'title' => 'Testimonials',
	'fields' => array(
		array(
			'key' => 'field_631d3d8544bd3',
			'label' => 'Your Name',
			'name' => 'testimonial_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => 'Example: Mary P.',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 1,
			'show_column_sortable' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
		array(
			'key' => 'field_631d4688b8a23',
			'label' => 'Your Comments',
			'name' => 'testimonial_comments',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
		array(
			'key' => 'field_631d470ab8a25',
			'label' => 'Puppy Photo',
			'name' => 'testimonial_photo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'uploader' => 'wp',
			'acfe_thumbnail' => 1,
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'uploadedTo',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, jpeg, png',
			'show_column' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
		array(
			'key' => 'field_631d47f3b8a26',
			'label' => 'Puppy\'s Name',
			'name' => 'testimonial_puppys_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 1,
			'show_column_sortable' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
		),
		array(
			'key' => 'field_631d4895b8a27',
			'label' => 'Consent to Post on this Site',
			'name' => 'testimonial_consent_to_post_on_this_site',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => 'Yes, I consent. (Grant consent for us to post to this site. This includes name, puppy\'s name, photo, and comments.)',
			'default_value' => 0,
			'ui' => 0,
			'show_column' => 1,
			'show_column_sortable' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_631d4a26b8a28',
			'label' => 'Consent to Share on other Sites',
			'name' => 'testimonial_consent_to_share_on_other_sites',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => 'Yes, I Consent. (Grant consent for us to share this on other sites. For example: Facebook, Twitter, and Instagram. This includes name, puppy\'s name, photo, and comments.)',
			'default_value' => 0,
			'ui' => 0,
			'show_column' => 1,
			'show_column_sortable' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'testimonial',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'block_editor',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'slug',
		6 => 'format',
		7 => 'page_attributes',
		8 => 'categories',
		9 => 'tags',
		10 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1662867071,
));

endif;