<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63d5a47611739',
	'title' => 'Contact Us Fields',
	'fields' => array(
		array(
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_63d5a477d6655',
			'label' => 'First Name',
			'name' => 'first_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'First Name',
			'prepend' => '',
			'append' => '',
		),
		array(
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_63d5a539d6656',
			'label' => 'Last Name',
			'name' => 'last_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Last Name',
			'prepend' => '',
			'append' => '',
		),
		array(
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_63d5a55dd6657',
			'label' => 'Email',
			'name' => 'email',
			'aria-label' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Email',
			'prepend' => '',
			'append' => '',
		),
		array(
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_63d5a59cd6658',
			'label' => 'Phone Number',
			'name' => 'phone_number',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Example: 123-555-6789',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Phone',
			'prepend' => '',
			'append' => '',
		),
		array(
			'show_column_filter' => 1,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63d5a5d7d6659',
			'label' => 'Subscribe to Announcements',
			'name' => 'subscribe_to_announcements',
			'aria-label' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Subscribed' => 'Subscribe me to Announcements',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'allow_custom' => 0,
			'layout' => 'vertical',
			'toggle' => 0,
			'save_custom' => 0,
		),
		array(
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63d5ad0f66da1',
			'label' => 'Message',
			'name' => 'message',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Please include a message about yourself and why you\'re reaching out to Hurricane Creek Doodles.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'rows' => 10,
			'placeholder' => 'Message to owner',
			'new_lines' => 'br',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => '',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'For more information on our great pups or to inquire about upcoming litters, fill out this form. ',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1675727776,
));

endif;